security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
coa:
  host: ${OBJ_STORE_HOST}
  namespace: ${COA_NAMESPACE}
  object-store-psw: ${OBJ_STORE_PSW}
  object-store-id: ${OBJ_STORE_ID}
management:
  trace:
    http:
      include: TIME_TAKEN,RESPONSE_HEADERS
  endpoints:
    web:
      exposure:
        include: httptrace,metrics,prometheus,health

