name: Build and Test COA Large File Applications

permissions:
  contents: read
  
on:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spring:
    name: App Build and Test
    runs-on: ubuntu-latest
    env:
      ACTION_DEBUG: true

    steps:   
      
      # Setup Java Environment
      - name: Set up JDK 25
        uses: actions/setup-java@v1
        with:
          java-version: 25
          
          cache: maven
        
       
      - name: Build Spring Starters
        run: mvn install -P all --file ./spring-boot-starters/src/pom.xml

      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Build with Maven - COA Large File Service
        run: mvn -B install -P all --file src/coa-large-file-service/pom.xml

