# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability (COA Applications) Scan using Trivy Scanner and Push to Security Tab

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile COA Application
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t coa-application -f src/coa-application/Dockerfile .

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner COA Application
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: image
          image-ref: coa-application
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab COA Large File Application
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
          
      - name: Build an image from Dockerfile COA Large File Application
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t coa-large-file-api -f src/coa-large-file-service/Dockerfile .

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner COA Large File Application
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: image
          image-ref: coa-large-file-api
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab COA Large File Application
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
          